config/routes.rb
Cssbits::Application.routes.draw do
  
  devise_for :users

  resources :snippets

  match 's/:slug' => 'snippets#show', :as => 'permalink'

  root :to => 'snippets#new'

 
end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
  uniquify :permalink, :length => 10
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  # GET /snippets
  # GET /snippets.json
  def index
    @snippets = Snippet.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @snippets }
    end
  end

  # GET /snippets/1
  # GET /snippets/1.json
  def show
    if params[:slug]
      @snippet = Snippet.where(:permalink => params[:slug]).first
    else
      @snippet = Snippet.find(params[:id])
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @snippet }
    end
  end

  # GET /snippets/new
  # GET /snippets/new.json
  def new
    @snippet = Snippet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @snippet }
    end
  end

  # GET /snippets/1/edit
  def edit
    @snippet = Snippet.find(params[:id])
  end

  # POST /snippets
  # POST /snippets.json
  def create
    @snippet = Snippet.new(params[:snippet])

    respond_to do |format|
      if @snippet.save
        format.html { redirect_to permalink_path(@snippet.permalink), notice: 'Snippet was successfully created.' }
        format.json { render json: @snippet, status: :created, location: @snippet }
      else
        format.html { render action: "new" }
        format.json { render json: @snippet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /snippets/1
  # PUT /snippets/1.json
  def update
    @snippet = Snippet.find(params[:id])

    respond_to do |format|
      if @snippet.update_attributes(params[:snippet])
        format.html { redirect_to @snippet, notice: 'Snippet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @snippet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /snippets/1
  # DELETE /snippets/1.json
  def destroy
    @snippet = Snippet.find(params[:id])
    @snippet.destroy

    respond_to do |format|
      format.html { redirect_to snippets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/views/layouts/_head.html.erb
<meta charset="utf-8">
<title>CSS Bits</title>
<%= csrf_meta_tags %>

<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
<![endif]-->

<!-- Le styles -->
<style>
  body {
    padding-top: 40px; /* 60px to make the container go all the way to the bottom of the topbar */
    background-image: url(/assets/background2.png);
  }
</style>
<%= stylesheet_link_tag "application", :media => "all" %>

<!-- Le fav and touch icons -->
<link href="images/favicon.ico" rel="shortcut icon">
<link href="images/apple-touch-icon.png" rel="apple-touch-icon">
<link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
<link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
      <div class="container">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="/"><strong>.CSS</strong> Bits</a>
      <ul class="nav pull-right">
      <% if user_signed_in? %>  
        <li><a>Signed in as <%= current_user.email %> </a></li>
        <li class="divider-vertical"></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
          <ul class="dropdown-menu">
          <li><%= link_to "Profile", '#' %></li>  
          <li class="divider"></li>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>  
      <% else %>      
            <li><a href="/users/sign_up" class="btn btn-info">Sign Up</a></li>
            <li class="divider-vertical"></li>
            <li><a href="/users/sign_in" class="btn btn-info">Sign In</a></li>
            
          </ul>
        </li>
      <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_notice.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= render 'layouts/head' %>
  </head>
  <body>
    <%= render 'layouts/navigation' %>
    <!-- <%= render 'layouts/notice' %> -->
    <div class="container">
      <div class="content">
        <div class="hero-unit">
          <%= yield %>
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        
      </footer>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/snippets/_form.html.erb
<div class="form">
  <%= form_for(@snippet) do |f| %>
    <div class="inputer">
      <h3>HTML</h3>
      <%= f.text_area :html, :id => 'html_input' %>
    </div>
    <div class="inputer">
      <h3>CSS</h3>
      <%= f.text_area :css, :id => 'css_input' %>
    </div>
    <div style="clear:both;"></div>
    <div class="output">
      <h3>Output</h3>
      <iframe id="output" style="width:600px;height:400px;border:1px solid #ccc" frameborder="0"></iframe>
    </div>
    <% if @snippet.new_record? %>
    <div>
      <%= f.submit 'Save CSS Bit', :class => 'btn btn-primary btn-large' %>
    </div>
    <% end %>
  <% end %>
</div>

app/views/snippets/edit.html.erb
<h1>Editing snippet</h1>

<%= render 'form' %>

<%= link_to 'Show', @snippet %> |
<%= link_to 'Back', snippets_path %>

app/views/snippets/index.html.erb
<h1>Listing snippets</h1>

<table>
  <tr>
    <th>Html</th>
    <th>Css</th>
    <th>Permalink</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @snippets.each do |snippet| %>
  <tr>
    <td><%= snippet.html %></td>
    <td><%= snippet.css %></td>
    <td><%= snippet.permalink %></td>
    <td><%= link_to 'Show', snippet %></td>
    <td><%= link_to 'Edit', edit_snippet_path(snippet) %></td>
    <td><%= link_to 'Destroy', snippet, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Snippet', new_snippet_path %>

app/views/snippets/new.html.erb
<%= render 'form' %>

app/views/snippets/show.html.erb
<input type="text" value="<%= permalink_url(@snippet.permalink) %>" style="width: 400px;" />
<%= render 'form' %>